// Document Object Symbol Properties
export const DOCUMENT_KEY_SYMBOL = Symbol('DOCUMENT_KEY');
export const DOCUMENT_CONNECTIONS_SYMBOL = Symbol('DOCUMENT_CONNECTIONS');
export const DOCUMENT_GRAPHQL_TYPENAME = Symbol('DOCUMENT_GRAPHQL_TYPENAME');
